export const HERO_POST_GET_INITIATE = "HERO_POST_GET_INITIATE";
export const HERO_POST_GET_SCUCESS = "HERO_POST_GET_SCUCESS";
export const HERO_POST_GET_FAIL = "HERO_POST_GET_FAIL";

export const FEATURE_POST_GET_INITIATE = "FEATURE_POST_GET_INITIATE";
export const FEATURE_POST_GET_SCUCESS = "FEATURE_POST_GET_SCUCESS";
export const FEATURE_POST_GET_FAIL = "FEATURE_POST_GET_FAIL";

export const POST_GET_INITIATE = "POST_GET_INITIATE";
export const POST_GET_SCUCESS = "POST_GET_SCUCESS";
export const POST_GET_FAIL = "POST_GET_FAIL";

export const CATEGORY_POST_GET_INITIATE = "CATEGORY_POST_GET_INITIATE";
export const CATEGORY_POST_GET_SCUCESS = "CATEGORY_POST_GET_SCUCESS";
export const CATEGORY_POST_GET_FAIL = "CATEGORY_POST_GET_FAIL";

export const CATEGORY_POST_UPDATE_GET_INITIATE =
  "CATEGORY_POST_UPDATE_GET_INITIATE";

export const CATEGORY_HERO_POST_GET_SCUCESS = "CATEGORY_HERO_POST_GET_SCUCESS";

export const SEARCH_POST_GET_INITIATE = "SEARCH_POST_GET_INITIATE";
export const SEARCH_POST_GET_SCUCESS = "SEARCH_POST_GET_SCUCESS";
export const SEARCH_POST_GET_FAIL = "SEARCH_POST_GET_FAIL";

export const ALERT_INITIATE = "ALERT_INITIATE";
export const ALERT_OVER = "ALERT_OVER";

export const USER_AUTHENTICATION_INITIATE = "USER_AUTHENTICATION_INITIATE";
export const USER_AUTHENTICATION_SCUCESS = "USER_AUTHENTICATION_SCUCESS";
export const USER_AUTHENTICATION_FAIL = "USER_AUTHENTICATION_FAIL";

export const USER_SIGN_OUT_SCUCESS = "USER_SIGN_OUT_SCUCESS";

export const BLOG_POST_INITIATE = "BLOG_POST_INITIATE";
export const BLOG_POST_SCUCESS = "BLOG_POST_SCUCESS";
export const BLOG_IMAGE_UPLOAD_SCUCESS = "BLOG_IMAGE_UPLOAD_SCUCESS";
export const BLOG_POST_FAIL = "BLOG_POST_FAIL";
