export const HERO_POST_GET_INITIATE = "HERO_POST_GET_INITIATE";
export const HERO_POST_GET_SCUCESS = "HERO_POST_GET_SCUCESS";
export const HERO_POST_GET_FAIL = "HERO_POST_GET_FAIL";

export const FEATURE_POST_GET_INITIATE = "FEATURE_POST_GET_INITIATE";
export const FEATURE_POST_GET_SCUCESS = "FEATURE_POST_GET_SCUCESS";
export const FEATURE_POST_GET_FAIL = "FEATURE_POST_GET_FAIL";

export const POST_GET_INITIATE = "POST_GET_INITIATE";
export const POST_GET_SCUCESS = "POST_GET_SCUCESS";
export const POST_GET_FAIL = "POST_GET_FAIL";

export const CATEGORY_POST_GET_INITIATE = "CATEGORY_POST_GET_INITIATE";
export const CATEGORY_POST_GET_SCUCESS = "CATEGORY_POST_GET_SCUCESS";
export const CATEGORY_POST_GET_FAIL = "CATEGORY_POST_GET_FAIL";

export const CATEGORY_HERO_POST_GET_SCUCESS = "CATEGORY_HERO_POST_GET_SCUCESS";
